# Use the official Ubuntu 20.04 as a base image
FROM ubuntu:20.04

# Set environment variables to prevent prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install necessary packages
RUN apt-get update && apt-get install -y \
    sudo \
    openssh-server \
    vim \
    wget \
    curl \
    net-tools \
    iputils-ping \
    gnupg \
    software-properties-common

# Create users hadoop and spark with passwordless sudo
RUN useradd -m -s /bin/bash hadoop && \
    useradd -m -s /bin/bash spark && \
    useradd -m -s /bin/bash airflow && \
    echo 'hadoop ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    echo 'spark ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    echo 'airflow ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Expose the specified ports
EXPOSE 50070 50071 50072 50073  8020 8021 8022 8023 8024 \
       9000 9001 9002 9003 9004 9864 9865 9866 9867 9868 22 \
       2180 2181 2182 2183 9001 3888 3889 3890 3891 3887 3881 2887 2886 2888 2889 50076 9871 2182 2183 \
       8486 8487 8488 8485 8482 2184 2887 2886 2885 9865 9866 9867 9868 9872 9873

# Start SSH service
RUN mkdir /var/run/sshd

CMD ["/usr/sbin/sshd", "-D"]